[package]
name = "hydrogen"
version = "0.0.1"
authors = [
    "DeerSoftware <contact@deersoftware.dev>",
    "Nashira Deer <nashiradeer@deersoftware.dev>",
]
edition = "2021"
description = "Hydrogen is a Discord bot made to entertain your server members."
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["discord", "lavalink", "music"]
publish = false

[dependencies]
async-trait = "0.1.68"
futures = "0.3.28"
http = "0.2.9"
rustls = "0.21.0"
serde_json = "1.0.99"
tokio-rustls = "0.24.1"
tracing = "0.1.37"
tungstenite = "0.19.0"

[dependencies.async-tungstenite]
package = "async-tungstenite"
version = "0.22.2"
features = [
    "tokio-runtime",
    "tokio-rustls-webpki-roots"
]

[dependencies.serde]
package = "serde"
version = "1.0.160"
features = [
    "derive"
]

[dependencies.serenity]
package = "serenity"
version = "0.11.5"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "voice",
    "rustls_backend",
]

[dependencies.tokio]
package = "tokio"
version = "1.27.0"
features = ["macros", "rt-multi-thread"]

[dependencies.tracing-subscriber]
package = "tracing-subscriber"
version = "0.3.17"
features = [
    "env-filter"
]
