[package]
name = "hydrogen"
version = "0.0.1"
authors = [
    "DeerSoftware <contact@deersoftware.dev>",
    "Nashira Deer <nashiradeer@deersoftware.dev>",
]
edition = "2021"
description = "Hydrogen is a Discord bot made to entertain your server members."
readme = "README.md"
license = "GPL-3.0-only"
keywords = ["discord", "lavalink", "music"]
publish = false

[dependencies]
rustls = "0.21.0"

[dependencies.serenity]
package = "serenity"
version = "0.11.5"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "http",
    "model",
    "utils",
    "voice",
    "rustls_backend",
]

[dependencies.tokio]
package = "tokio"
version = "1.27.0"
features = ["macros", "rt-multi-thread"]
