services:
  lavalink:
    image: nashiradeer/lavalink-openj9:3.7.10
    container_name: lavalink
    restart: unless-stopped
    environment:
      - SERVER_PORT=2333
      - LAVALINK_SERVER_PASSWORD=youshallnotpass
    networks:
      - lavalink
  hydrogen:
    image: nashiradeer/hydrogen:0.0.1-alpha.4
    container_name: hydrogen
    restart: unless-stopped
    networks:
      - lavalink
    environment:
      - HYDROGEN_DISCORD_TOKEN=
      - HYDROGEN_LAVALINK=lavalink:2333,youshallnotpass,no
      # The following environment variables isn't required and it's not recommended to add them unless you know what you're doing.
      - HYDROGEN_DEFAULT_LANGUAGE=en-US
      - HYDROGEN_LANGUAGE_PATH=/app/lang
    depends_on:
      - lavalink
networks:
  lavalink:
    name: lavalink
